services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    env_file:
      - .env
    volumes:
      - test-data:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
volumes:
  test-data: